### ISSUE TITLE
訳語がうまく表示されない単語がある

### ISSUE THREAD

**Issue by skytomo221** [skytomo221/LineparineOneToManyJsonDictionary#4]
訳語に品詞が書かれていないため，
うまく変換できない単語が340単語存在する．
以下にその単語を示す．

- alasakirfinaz
- alcirt
- alcirta
- alekiunka
- AN
- aneokafanka
- aneokartka
- aneokaxtaka
- aneokka
- aneoklikka
- aneokxenka
- aneokyrfka
- aneoqaintika
- anfenchayrhka
- anfenchekxka
- anfenhikka
- anfentihafarka
- anfentikenti
- anfentikknoryka
- anfentiklirka
- anfentikxyrtka
- anfentkakka
- anfirxka
- ankafentika
- ankaxantaka
- anlekarnork
- anlekkar
- anlikkaxirka
- anliklirk
- anlirkfirea
- anlirkfork
- anlirkkaxkarta
- anlyrkka
- anorka
- anorkanorka
- anxantarxnartka
- anxantfank
- anxanti'ir
- anxantkafirtka
- anxantkatka
- anxantkaxirnk
- anxantkyrfa
- anxekafirchka
- anxekka
- anxenkartka
- anxenkfarka
- anxenknorka
- anxenkyrhka
- anxikaxortka
- anxirka
- anxirklirkka
- anxkurcirka
- anyfka
- anyfkafanka
- anyfkafentika
- anyfkaka
- anyfkangneoka
- anyfkatka
- anyfkaxantark
- anyfkayfka
- anyfklekka
- anyfkorxirnft
- astaneuzirnas
- chystischyettinecerlkyde
- curl
- desnojuocnea
- dicceli'a
- dieest
- diejis
- dielys
- diesnisn
- dirbanarde
- dirost
- dislators
- dislatorsas
- distul
- diursans
- dolisn
- doviv
- durier
- dusnod
- duvuv
- dydusn
- dyjisn
- dyrul
- dysun
- dyten
- dyved
- enxerfinisn
- e'ri
- eri
- erli
- etulyo
- etysn
- exchew
- facarlya
- fakaschexfil
- falcismaleru
- falsirs
- farn'axart
- feandecar
- fhisli'a
- forttudey
- fyrtlaikcau
- gytyuv
- harkar
- harkenxtarsne
- hartlyrtfarlea
- hatalyrt
- hoffen
- hyrcorfilen
- ietostidyst
- ievod
- ilern
- ilernu
- ilirn
- imilerkirt
- in-
- inggland
- i'ri
- ischydzette
- jalfkark
- JLPY
- juocinea
- klenan
- kosnust
- kravi
- kydyp
- kyroncheoxtax
- la cene-niv-sulaun-kyde-y
- la chertif-tesyj-y
- la danqa-snidost-apia-y
- la eo-alse-akrantierl
- la eo-alse-elmi'esm-y
- la hamie-roft-y
- la jiesnyp-en'iarer-y
- la jyvied-jiesnyp-y
- la kosnust-tydiv-y
- la pazu-sysit-y
- la stynyr-adils
- la xelken-under-nitud-en'iar
- la zirl-zant-yapia-y
- labasfina
- lael
- lai
- lakeule
- lay
- LDesL
- ldzudz
- lmurk
- lodun
- lorier
- lovul
- loysn
- lsans
- lubes
- lubom
- lufed
- lujos
- lujyk
- lukrifh
- lulen
- lumavh
- lumub
- lunisn
- lurykr
- luskcifasan
- luthykr
- lutit
- luvodz
- luxod
- luzedz
- luzux
- LXUNEI
- lysted
- lyvaz
- malegerl
- mol'o
- narju
- naxart
- naxtailj'etas
- neffirain
- nen
- nenil
- nidyr
- niedon
- nielyp
- nieriet
- niesnisn
- nietod
- nievev
- nievus
- nismalchdesk
- nunien
- nyey
- nystien
- olys
- osied
- ostyst
- oved
- ovop
- rejiek
- relij
- restep
- rolud
- roluk
- rosnyx
- roxusn
- rusuv
- ryckir
- ryjisn
- rylusn
- rynil
- selij
- sernerlxpais
- sides
- sieod
- sierost
- sievys
- sinon
- sinot
- siriej
- sisnes
- sisnost
- sistys
- siuna
- sivyn
- skarna
- sniejysn
- snieliep
- sniepest
- snierur
- sniestix
- snijiej
- sninist
- snisnyst
- snixek
- snoter
- snovij
- snudist
- snujisn
- snujon
- snulel
- snulid
- snuret
- snusus
- snuxen
- snydet
- snydyr
- snyky
- snyny
- snysnud
- snystost
- snytij
- snyxus
- sodesn
- sojel
- sojex
- sojin
- starnkax
- staxerfter
- stedys
- stejiesn
- steliest
- stiepir
- stieyst
- stijul
- stinied
- stinuk
- stipiesn
- stisir
- stisniel
- stisniev
- stistisn
- stistyst
- stitol
- stokyd
- stonid
- stopep
- stopiev
- stopy
- stovies
- studev
- stune
- stunies
- stydet
- stytiex
- styyk
- sulis
- suo
- surun
- sustiej
- sustyr
- syu
- usosn
- uxun
- velud
- vesov
- vielyr
- vierist
- viokk
- vipyx
- visnid
- vistust
- vupov
- vykot
- vyresn
- vyxik
- xal'o
- xaluwaloajerlerm
- xan-
- xkadz
- xkardzy
- xkars
- xkarse
- xl.
- xnizopitli
- xostit
- xul
- xule
- xuliv
- xunuv
- xurl
- xustyj
- xyrl
- xyvoj
- xyxost
- yans
- yapia
- ycus
- ydun
- yesleoneunsar
- yled
- ylesnalegerl
- yrfarlkarfar
- yrfcxykliurs
- yrkana
- yrskestyrsy
- yrstorxa
- zhue

**Comment by Fafsfalira** [comment]
結構遅くなりましたが、一応品詞が付けられていない単語全てに品詞付けをしたので報告しておきます。

**Comment by skytomo221** [comment]
おお！ありがとうございます．
これでVersion 2.0のタスクがすべて完了しました．（やったー）
